"""Every specified capability has an implementation module. Tests import this map."""

from __future__ import annotations

SPEC_IMPLEMENTATIONS: dict[str, str] = {
    "goal_processor_loop": "agent_kernel.runtime.AgentRun",
    "deterministic_shell": "agent_kernel.lifecycle.Lifecycle",
    "lifecycle_state_machine": "agent_kernel.lifecycle.ALLOWED_TRANSITIONS",
    "agent_vs_os_ownership": "agent_os.AgentOS",
    "task_contract": "agent_kernel.contracts.task.AgentTaskContract",
    "result_contract": "agent_kernel.contracts.result.AgentResult",
    "plan_dag": "agent_kernel.contracts.plan.Plan",
    "plan_validator_checks": "agent_kernel.plan_validate.validate_plan",
    "plan_compiler": "agent_kernel.plan_validate.compile_plan",
    "dag_scheduler_leases": "agent_kernel.scheduler.run_dag",
    "four_validation_levels": "agent_kernel.validators.input_validation",
    "independent_step_validator": "agent_kernel.validators.step_validation",
    "goal_acceptance": "agent_kernel.validators.goal_validation",
    "context_compiler": "agent_kernel.context_compiler.compile_context",
    "governed_memory": "agent_kernel.memory.GovernedMemory",
    "runtime_bundle": "agent_kernel.contracts.runtime_bundle.RuntimeBundle",
    "failure_envelope": "agent_kernel.contracts.failure_envelope.FailureEnvelope",
    "typed_errors": "agent_kernel.errors.AgentError",
    "recovery_matrix": "agent_kernel.recovery.decide_recovery",
    "task_lease": "agent_kernel.contracts.lease.TaskLease",
    "budget_envelope": "agent_kernel.contracts.budget.BudgetEnvelope",
    "authority_grant": "agent_kernel.contracts.authority.AuthorityGrant",
    "model_capability_router": "agent_kernel.model_router.select_model",
    "coordination_safety": "agent_kernel.coordination.CoordinationGuard",
    "resilience": "agent_kernel.resilience.CircuitBreaker",
    "contract_migration": "agent_kernel.migration.SchemaMigrator",
    "graceful_degradation": "agent_kernel.degradation.degrade",
    "slo": "agent_kernel.slo.SLOTracker",
    "design_by_contract": "agent_kernel.design_by_contract.CapabilityContract",
    "narrow_ports": "agent_kernel.ports.ChatModelPort",
    "instance_per_run": "agent_kernel.runtime.Agent",
    "identity_agntcy": "agent_os.IdentityRegistry",
    "tenant_isolation": "agent_os.TenantIsolation",
    "secrets_scoped": "agent_os.SecretVault",
    "global_quotas": "agent_os.QuotaBoard",
    "sandbox_gateway": "agent_os.Sandbox",
    "approval_routing": "agent_os.ApprovalRouter",
    "append_only_ledger": "agent_os.AppendOnlyLedger",
    "durable_checkpoint_sqlite": "agent_os.SqliteCheckpoint",
    "postgres_adapter": "adapters.postgres.PostgresCheckpointAdapter",
    "redis_streams": "adapters.redis_streams.RedisStreamsAdapter",
    "object_store": "agent_os.FileArtifactStore",
    "otel": "adapters.observability.OpenTelemetryAdapter",
    "pgvector": "adapters.observability.PgVectorAdapter",
    "rest_adapter": "adapters.protocol.RestAdapter",
    "grpc_adapter": "adapters.protocol.GrpcAdapter",
    "queue_adapter": "adapters.protocol.EventQueueAdapter",
    "mcp_adapter": "adapters.protocol.McpAdapter",
    "a2a_adapter": "adapters.protocol.A2AAdapter",
    "agntcy_adapter": "adapters.protocol.AgntcyAdapter",
    "langgraph_adapter": "adapters.protocol.LangGraphAdapter",
    "local_adapter": "adapters.protocol.LocalProcessAdapter",
    "model_adapters": "adapters.models.LocalChatModel",
    "tool_supply_chain": "adapters.models.SandboxToolAdapter",
    "evaluation_os": "evaluations.release_gate",
    "eval_families": "evaluations.EVAL_FAMILIES",
    "release_pipeline": "release.run_release",
    "controlled_improvement": "evolution.ImprovementPipeline",
    "health_kill_switch": "agent_os.Health",
    "canonical_protocol": "agent_kernel.protocol.CANONICAL_TYPES",
}
